uploads = []
outputs = []

[[generated]]
id = "i7xepTbuhTDacCqEYTVCL"
uri = "file://attached_assets/leio-icon.png"
type = "image"
title = "leio-capi-app-icon"

[[generated]]
id = "CqF55YsEyBc9U5ggNGu3V"
uri = "file://artifacts/leio/assets/images/capi-reading.png"
type = "image"
title = "capi reading book mascot"
