uploads = []

[[generated]]
id = "i7xepTbuhTDacCqEYTVCL"
uri = "file://attached_assets/leio-icon.png"
type = "image"
title = "leio-capi-app-icon"

[[generated]]
id = "CqF55YsEyBc9U5ggNGu3V"
uri = "file://artifacts/leio/assets/images/capi-reading.png"
type = "image"
title = "capi reading book mascot"

[[generated]]
id = "JGfsAJjBJGqg_I9fuazql"
uri = "file://artifacts/leio/assets/images/capi-romance.png"
type = "image"
title = "capi romance variant"

[[generated]]
id = "dZ-MEy2C3lXGmhWmAJf1Z"
uri = "file://artifacts/leio/assets/images/capi-scifi.png"
type = "image"
title = "capi scifi variant"

[[outputs]]
id = "5orAXMCUouqxR4sntrPWe"
uri = "file://.local/outputs/Preparado-Context.pdf"
type = "pdf"
title = "Preparado Context.pdf"
