const colors = {
  light: {
    text: "#0A0A0A",
    tint: "#CDFF00",
    background: "#FAFAF8",
    foreground: "#0A0A0A",
    card: "#F0F0EE",
    cardForeground: "#0A0A0A",
    primary: "#0A0A0A",
    primaryForeground: "#CDFF00",
    secondary: "#E8E8E6",
    secondaryForeground: "#0A0A0A",
    muted: "#E8E8E6",
    mutedForeground: "#666666",
    accent: "#CDFF00",
    accentForeground: "#0A0A0A",
    destructive: "#FF5733",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0DE",
    input: "#F0F0EE",
    volt: "#CDFF00",
    coral: "#FF5733",
  },
  dark: {
    text: "#FAFAF8",
    tint: "#CDFF00",
    background: "#0A0A0A",
    foreground: "#FAFAF8",
    card: "#141414",
    cardForeground: "#FAFAF8",
    primary: "#CDFF00",
    primaryForeground: "#0A0A0A",
    secondary: "#1A1A1A",
    secondaryForeground: "#FAFAF8",
    muted: "#1A1A1A",
    mutedForeground: "#888888",
    accent: "#CDFF00",
    accentForeground: "#0A0A0A",
    destructive: "#FF5733",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1A1A1A",
    volt: "#CDFF00",
    coral: "#FF5733",
  },
  radius: 12,
};

export default colors;
